// <auto-generated />
namespace CabicsSubscription.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrationv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationv4));
        
        string IMigrationMetadata.Id
        {
            get { return "201806172323534_migrationv4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
